/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AudioApp: typeof import('./src/components/audio-app.vue')['default']
    MediaLoader: typeof import('./src/components/media-loader.vue')['default']
    NutActionSheet: typeof import('nutui-uniapp/components/actionsheet/actionsheet.vue')['default']
    NutButton: typeof import('nutui-uniapp/components/button/button.vue')['default']
    NutIcon: typeof import('nutui-uniapp/components/icon/icon.vue')['default']
    NutSwiper: typeof import('nutui-uniapp/components/swiper/swiper.vue')['default']
    NutSwiperItem: typeof import('nutui-uniapp/components/swiperitem/swiperitem.vue')['default']
    NutTabbar: typeof import('nutui-uniapp/components/tabbar/tabbar.vue')['default']
    NutTabbarItem: typeof import('nutui-uniapp/components/tabbaritem/tabbaritem.vue')['default']
    TabBar: typeof import('./src/components/tab-bar.vue')['default']
  }
}
