/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    NutTabbar: typeof import('nutui-uniapp/components/tabbar/tabbar.vue')['default']
    NutTabbarItem: typeof import('nutui-uniapp/components/tabbaritem/tabbaritem.vue')['default']
    TabBar: typeof import('./src/components/tab-bar.vue')['default']
  }
}
